### ISSUE TITLE
Need links for portfolio's and Mike's LinkedIn

### ISSUE THREAD

**Issue by jongrim** [hzemzem/Lively-Music-App#1]
I thought it would be nice to add a contributor table to the README so that anyone viewing the project can quickly see the team members. Additionally, I wanted to include links to things like GitHub profiles, LinkedIn, and personal portfolio sites to promote each individual in case a recruiter is viewing the project.

To finish this I need:

- @mikehashi LinkedIn address
- URL for each person's portfolio, if you have one.

Feel free to comment with your thoughts on the contributor table, or feel free to go edit it yourself if you want to update the info.

**Comment by mikehashi** [comment]
https://www.linkedin.com/in/michael-hashimoto-a644224a/ for my linkedin

**Comment by jongrim** [comment]
Thanks Mike. I updated your LinkedIn link on the table. I'll leave this open for now in case anyone has anything they want to add.

**Comment by jongrim** [comment]
Closing now because I think I have everyone's current links
